# Generated by Django 5.2.3 on 2025-06-18 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cotacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moeda', models.CharField(choices=[('BRL', 'Real Brasileiro'), ('EUR', 'Euro'), ('JPY', 'Iene Japonês')], help_text='A moeda para a cotação (ex: BRL, EUR, JPY).', max_length=3)),
                ('valor', models.DecimalField(decimal_places=4, help_text='O valor da cotação em relação ao USD.', max_digits=10)),
                ('data', models.DateField(help_text='A data da cotação.')),
            ],
            options={
                'verbose_name': 'Cotação',
                'verbose_name_plural': 'Cotações',
                'ordering': ['-data', 'moeda'],
                'unique_together': {('moeda', 'data')},
            },
        ),
    ]
